######################################################################
#                                                                    #
#                            KINGDOMCRAFT                            #
#                   Created by iGufGuf, Copyrighted                  #
#                          ----------------                          #
#                 Credits would really be apreciated                 #
#                                                                    #
######################################################################

#DONT CHANGE THIS, IT WILL BE USED TO AUTO-UPDATE THE CONFIG
version: {VERSION}

#Prefix when you are not in a kingdom
default-prefix: '&f[&6New&f] &7'

#Enable the plugin for only some single worlds (case sensitive)
worlds: false
world-list:
- world

#Show Offline players in /k info
info-offline-players: true

#Make player use /spawn when he leaves or get kicked from a kingdom.
spawn-on-kingdom-leave: true

#Make players teleport to the kingdom spawn when joining a kingdom.
spawn-on-kingdom-join: true

#Cooldown in seconds for teleporting to kingdom spawn (0 = default), no waiting with kindom.teleport.bypass
tp-delay: 5

#true = use the below channel system, DON'T USE ANY OTHER CHAT PLUGIN!
#false = use another chat plugin.
chat-system: true

#the chat format when the channels are not used
nochannels-format: '&7{RANK}{KINGDOM}{KINGDOMRANK} &b{NAME} &8\u00BB &7{MESSAGE}'

# The channel where you talk in when not in a kingdom, can't be a kingdom only channel!
# Remove this to make players not able to talk when not in a kingdom!
# possible chat format variables:
# playe, username, message
# kingdom, kingdomname, kingdomprefix, kingdomsuffix
# kingdomrank, kingdomranksuffix, kingdomrankprefix
# (vault support:) prefix, suffix
nokingdom-channel: 'public'
channels:
    enabled: true
    
    #Default channel for kingdom, cannot be removed or replaced
    kingdom:
        format: '&8[K]&7{prefix}{kingdomrank} &7{player} &8\u00BB &7{message}'

        #Only members of your kingdom will see this
        kingdom-only: true

        #The channel where you talk in without a message prefix
        default: true

    public:

        #make players not able to toggle this channel!
        alwayson: true

        #the format that will display when the player is talking in this channel
        format: '&8[P]&7{prefix}{kingdom}{kingdomrank} &7{player} &8\u00BB &7{message}'

        #Prefix before message to send a message in this channel
        message-prefix: '!'
        
    roleplay:
        format: '&8[R]&7{prefix} &7{player} &8\u00BB &7{message}&7'
        message-prefix: '#'
        
    trade:
        format: '&8[T]&7{prefix} &7{name} &8\u00BB &7{message}'
        message-prefix: '$'

    admin:
        format: '&4[A]{prefix} &7{name} &8\u00BB &7{message}'
        #Permission to watch & talk in this channel: kingdom.channel.<channelname>
        permission: true
        message-prefix: '@'