######################################################################
#                                                                    #
#                            KINGDOMCRAFT                            #
#                Created by Joris Guffens, Copyrighted               #
#                        --------------------                        #
#                             version 6.0                            #
#                                                                    #
#                       https://kingdomcraft.nl                      #
######################################################################


database:
    driver: 'org.h2.Driver'
    url: 'jdbc:h2:file:./plugins/KingdomCraft/database.h2'
    username: 'kingdomcraft'
    password: ''