######################################################################
#                                                                    #
#                            KINGDOMCRAFT                            #
#                Created by Joris Guffens, Copyrighted               #
#                        --------------------                        #
#                             version 6.0                            #
#                                                                    #
#                       https://kingdomcraft.nl                      #
######################################################################


database:
    driver: 'org.sqlite.JDBC'
    url: 'jdbc:sqlite:./plugins/KingdomCraft/database.sqlite'
    username: ''
    password: ''