######################################################################
#                                                                    #
#                            KINGDOMCRAFT                            #
#                Created by Joris Guffens, Copyrighted               #
#                        --------------------                        #
#                             version 6.0                            #
#                                                                    #
#                       https://kingdomcraft.nl                      #
######################################################################

settings:

    # a list of worlds this plugin is enabled in, remove to allow all worlds
    worlds:
    - world
    - world_nether
    - world_the_end

    friendly-fire-relationships:
    - ally
    - truce



    # commands to be executed when an event happens
    # prefix with CONSOLE to execute this in the console
    # e.g. CONSOLE money give {player} 1000
    events:
        kingdom_join:
        - k spawn
        - CONSOLE clearinv {player}

        kingdom_leave:
        - spawn
        - CONSOLE clearinv {player}

        respawn:
        - k spawn

    messages:
        join: '&e{kingdom_prefix}{rank_prefix}{player} &ejoined the server.'
        leave: '&e{kingdom_prefix}{rank_prefix}{player} &equit the server.'
        death: '&e{kingdom_prefix}{rank_prefix}{player} &edied.'
        kill: '&e{kingdom_prefix}{rank_prefix}{player} &ewas killed by
            {killer_kingdom_prefix}{killer_rank_prefix}{killer_player} &ewith weapon {killer_weapon}&e.'

# DO NOT CHANGE THIS SECTION IF YOU DO NOT KNOW WHAT YOU ARE DOING!
database:
    driver: 'org.h2.Driver'
    url: 'jdbc:h2:file:./plugins/KingdomCraft/database.h2'
    username: 'kingdomcraft'
    password: ''
