name: 'KingdomCraft'
author: iGufGuf
version: "6.0"
description: 'The Ultimate Kingdom Plugin'
softdepend: [Vault, WorldEdit, WorldGuard]
main: com.guflan.kingdomcraft.bukkit.KingdomCraft
commands:
    kingdomcraft:
      aliases: [k, kd, kdc, kingdoms, kingdom]