name: 'KingdomCraft'
author: iGufGuf
version: "6.0"
description: 'The Ultimate Kingdom Plugin'
softdepend: [Vault, WorldEdit, WorldGuard]
main: com.igufguf.kingdomcraft.KingdomCraft
commands:
    kingdom:
      aliases: [k, kd, kdc, kingdoms, kingdomcraft]