######################################################################
#                                                                    #
#                            KINGDOMCRAFT                            #
#                Created by Joris Guffens, Copyrighted               #
#                        --------------------                        #
#                             version 6.0                            #
#                                                                    #
#                       https://kingdomcraft.be                      #
######################################################################

settings:

    nokingdom:
        display: '&eHobo'
        prefix: '&7[&eHobo&7]'
        suffix: ''

    # a list of worlds this plugin is enabled in, remove to allow all worlds
    worlds:
    - world
    - world_nether
    - world_the_end

    # Enable the chat even if the world is not enabled
    enable-chat-in-disabled-worlds: false

    friendly-fire: false

    # include these relationships in the friendly fire check
    friendly-fire-relationships:
    - ally
    - truce

    # Respawn at the kingdom spawn when you die
    respawn-at-kingdom: true

    # Delay for teleport commands like /k spawn
    teleport-delay: 5

    # commands to be executed when an event happens
    # prefix with CONSOLE to execute this in the console
    # e.g. CONSOLE money give {username} 1000
    events:
        kingdom-join:
        - CONSOLE k tpspawn {username}
        - CONSOLE clearinv {username}

        kingdom-leave:
        - CONSOLE k tpspawn {username}
        - CONSOLE clearinv {username}

    # Show the custom join and leave messages (defined below) only for your own kingdom members
    join-and-leave-kingdom-only: false

    messages:
        join: '&e{kingdom_prefix}{rank_prefix}{player} &ejoined the server.'
        leave: '&e{kingdom_prefix}{rank_prefix}{player} &equit the server.'
        death: '&e{kingdom_prefix}{rank_prefix}{player} &edied.'
        kill: '&e{kingdom_prefix}{rank_prefix}{player} &ewas killed by {killer_kingdom_prefix}{killer_rank_prefix}{killer_player}&e.'

# DO NOT CHANGE THIS SECTION IF YOU DO NOT KNOW WHAT YOU ARE DOING!
database:
    driver: 'org.h2.Driver'
    url: 'jdbc:h2:file:./plugins/KingdomCraft/database.h2;AUTO_SERVER=TRUE'
    username: 'kingdomcraft'
    password: ''
