######################################################################
#                                                                    #
#                            KINGDOMCRAFT                            #
#                Created by Joris Guffens, Copyrighted               #
#                        --------------------                        #
#                             version 6.0                            #
#                                                                    #
#                       https://kingdomcraft.be                      #
######################################################################

settings:

    # enter the filename (without .yml) for the messages
    language: 'en'

    # command aliases
    command-aliases: [k, kd, kdc, kingdom]

    nokingdom:
        display: '&eHobo'
        prefix: '&7[&eHobo&7]'
        suffix: ''

    # Enable the chat even if the world is not enabled
    enable-chat-in-disabled-worlds: false

    friendly-fire: false

    # include these relationships in the friendly fire check
    friendly-fire-relationships:
    - ally
    - truce

    # Respawn at the kingdom spawn when you die
    respawn-at-kingdom: true

    # Delay for teleport commands like /k spawn
    teleport-delay: 5

    # commands to be executed when an event happens
    # prefix with CONSOLE to execute this in the console
    # e.g. CONSOLE money give {username} 1000
    events:
        kingdom-join:
        - CONSOLE k tpspawn {username}

        kingdom-leave:
        - CONSOLE k tpspawn {username}

    # Show the custom join and leave messages (defined below) only for your own kingdom members
    join-and-leave-kingdom-only: false

    messages:
        join: '&e{kingdom_prefix}{rank_prefix}{username} &ejoined the server.'
        leave: '&e{kingdom_prefix}{rank_prefix}{username} &equit the server.'
        death: '&e{kingdom_prefix}{rank_prefix}{username} &edied.'
        kill: '&e{kingdom_prefix}{rank_prefix}{username} &ewas killed by {killer_kingdom_prefix}{killer_rank_prefix}{killer_username}&e.'
        kill-weapon: '&e{kingdom_prefix}{rank_prefix}{username} &ewas killed by {killer_kingdom_prefix}{killer_rank_prefix}{killer_username} &ewith weapon {weapon}&e.'

    # For times or dates that are displayed in the plugin
    timezone: 'Europe/Brussels'
    date-format: 'yyyy-MM-dd'
    time-format: 'HH:mm'

    # Update display names with the kingdom prefix and suffix
    update-display-names: true

# DO NOT CHANGE THIS SECTION IF YOU DO NOT KNOW WHAT YOU ARE DOING!
database:
    driver: 'org.h2.Driver'
    url: 'jdbc:h2:file:./plugins/KingdomCraft/data/database.h2'
    username: 'kingdomcraft'
    password: ''
