name: 'KingdomCraft'
author: iGufGuf
version: ${pluginVersion}
description: 'The Ultimate Kingdom Plugin'
softdepend: [Vault, WorldEdit, WorldGuard]
main: com.guflan.kingdomcraft.bukkit.KingdomCraftBukkitPlugin
commands:
    kingdomcraft:
      aliases: [k, kd, kdc, kingdoms, kingdom]